/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SolutionService } from "../solution.service";
import { SolutionCreateInput } from "./SolutionCreateInput";
import { Solution } from "./Solution";
import { SolutionFindManyArgs } from "./SolutionFindManyArgs";
import { SolutionWhereUniqueInput } from "./SolutionWhereUniqueInput";
import { SolutionUpdateInput } from "./SolutionUpdateInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";

export class SolutionControllerBase {
  constructor(protected readonly service: SolutionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Solution })
  async createSolution(
    @common.Body() data: SolutionCreateInput
  ): Promise<Solution> {
    return await this.service.createSolution({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        user: true,
        questionId: true,
        solutionText: true,
        timestamp: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Solution] })
  @ApiNestedQuery(SolutionFindManyArgs)
  async solutions(@common.Req() request: Request): Promise<Solution[]> {
    const args = plainToClass(SolutionFindManyArgs, request.query);
    return this.service.solutions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        user: true,
        questionId: true,
        solutionText: true,
        timestamp: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Solution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async solution(
    @common.Param() params: SolutionWhereUniqueInput
  ): Promise<Solution | null> {
    const result = await this.service.solution({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        user: true,
        questionId: true,
        solutionText: true,
        timestamp: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Solution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSolution(
    @common.Param() params: SolutionWhereUniqueInput,
    @common.Body() data: SolutionUpdateInput
  ): Promise<Solution | null> {
    try {
      return await this.service.updateSolution({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          user: true,
          questionId: true,
          solutionText: true,
          timestamp: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Solution })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSolution(
    @common.Param() params: SolutionWhereUniqueInput
  ): Promise<Solution | null> {
    try {
      return await this.service.deleteSolution({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          user: true,
          questionId: true,
          solutionText: true,
          timestamp: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: SolutionWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        commentText: true,
        timestamp: true,
        user: true,

        solution: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  async connectComments(
    @common.Param() params: SolutionWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateSolution({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  async updateComments(
    @common.Param() params: SolutionWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateSolution({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  async disconnectComments(
    @common.Param() params: SolutionWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateSolution({
      where: params,
      data,
      select: { id: true },
    });
  }
}
